const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktop", {
  isElectron: true,
  onExportBackup: (cb) => ipcRenderer.on("menu:export-backup", cb),
  onImportBackup: (cb) => ipcRenderer.on("menu:import-backup", cb),
  onSavedPrograms: (cb) => ipcRenderer.on("menu:saved-programs", cb),
  onRestoreDefaults: (cb) => ipcRenderer.on("menu:restore-defaults", cb),
  saveBackupDialog: (defaultName) => ipcRenderer.invoke("dialog:save-backup", defaultName),
  openBackupDialog: () => ipcRenderer.invoke("dialog:open-backup"),
  writeFile: (filePath, content) => ipcRenderer.invoke("fs:write-file", filePath, content),
  readFile: (filePath) => ipcRenderer.invoke("fs:read-file", filePath),
  exportPdf: (defaultName, landscape) => ipcRenderer.invoke("export:pdf", defaultName, landscape),
  exportExcel: (defaultName, sheets) => ipcRenderer.invoke("export:excel", defaultName, sheets),
  exportScheduleExcel: (defaultName, teacherBlocks) => ipcRenderer.invoke("export:schedule-excel", defaultName, teacherBlocks),
  exportYillikPlanExcel: (defaultName, payload) => ipcRenderer.invoke("export:yillik-plan-excel", defaultName, payload),
  exportNormKadroExcel: (defaultName, payload) => ipcRenderer.invoke("export:norm-kadro-excel", defaultName, payload),
  exportGunlukPlanExcel: (defaultName, payload) => ipcRenderer.invoke("export:gunluk-plan-excel", defaultName, payload),
  exportWord: (defaultName, innerHtml, landscape) => ipcRenderer.invoke("export:word", defaultName, innerHtml, landscape),
  openXlsxDialog: () => ipcRenderer.invoke("dialog:open-xlsx"),
  importPlanXlsx: (filePath) => ipcRenderer.invoke("import:plan-xlsx", filePath),
  importEnvanterXlsx: (filePath) => ipcRenderer.invoke("import:envanter-xlsx", filePath),
  importPerformansXlsx: (filePath) => ipcRenderer.invoke("import:performans-xlsx", filePath),
  openPdfDialog: () => ipcRenderer.invoke("dialog:open-pdf"),
  importOgrenciPdf: (filePath) => ipcRenderer.invoke("import:ogrenci-pdf", filePath),
  importNotOrtalamaXlsx: (filePath) => ipcRenderer.invoke("import:not-ortalama-xlsx", filePath),
  openWordDialog: () => ipcRenderer.invoke("dialog:open-word"),
  importWordTable: (filePath) => ipcRenderer.invoke("import:word-table", filePath),
  importOgrenciWord: (filePath) => ipcRenderer.invoke("import:ogrenci-word", filePath)
});
